import Reveal from "@/components/ui/reveal";

const LAST_UPDATED = "July 4, 2026";

interface PrivacySection {
  title: string;
  paragraphs: string[];
}

const SECTIONS: PrivacySection[] = [
  {
    title: "1. Overview",
    paragraphs: [
      'This Privacy Policy explains how ElderOps ("ElderOps", "we", "us", or "our") collects, uses, and protects information when you visit the website located at elderops.net (the "Site") or contact us through it. We keep data collection to the minimum needed to respond to you — the Site has no user accounts, no advertising, and no analytics tracking.',
    ],
  },
  {
    title: "2. Information You Provide",
    paragraphs: [
      "Contact form. When you submit the form on our contact page, we receive the details you enter: your name, work email, company, what you are looking for, your focus area, and your message.",
      "Hiring Advisor. Before starting a conversation with our Hiring Advisor assistant, you provide your name, email, and optionally your company, which we use only to follow up on your hiring question. If you choose to share a recommendation with us, the details you typed — such as a project description or job description — are included so we can respond meaningfully.",
      "Scheduling. If you book a consultation, scheduling happens through Calendly's own booking window, and any details you enter there are collected by Calendly under its own privacy policy.",
    ],
  },
  {
    title: "3. Information Collected Automatically",
    paragraphs: [
      "We do not use analytics tools, advertising trackers, or social media pixels, and we do not build profiles of visitors.",
      "Some technical data is processed as an unavoidable part of serving a website: our hosting provider (Vercel) keeps standard server request logs, and the font services our pages load from (Fontshare and Google Fonts) receive standard connection data such as your IP address and browser type when the fonts are fetched.",
    ],
  },
  {
    title: "4. How We Use Your Information",
    paragraphs: [
      "We use the information you provide for one purpose: to respond to your inquiry and follow up on it. That includes answering questions, preparing recommendations or shortlists you have asked for, and scheduling conversations. We do not sell your information, share it with advertisers, or use it for marketing lists you have not asked to join.",
    ],
  },
  {
    title: "5. How Your Information Is Stored",
    paragraphs: [
      "The Site does not operate a customer database. When you submit the contact form or a Hiring Advisor request, your submission is converted into an email delivered to our team inbox (contact@elderops.net) and is retained there as ordinary business correspondence.",
      "Hiring Advisor conversations are generated by rule-based logic on our own infrastructure. Your chat is not sent to any artificial-intelligence service, and conversation history is not stored after you close the chat — it exists only in your browser during the session.",
    ],
  },
  {
    title: "6. Service Providers",
    paragraphs: [
      "We rely on a small number of providers to operate the Site, each receiving only what is necessary for its role: Vercel (website hosting and request handling), Resend, EmailJS, and FormSubmit (delivery of form submissions to our inbox as email), Calendly (consultation scheduling, only when you open the booking window), and Fontshare and Google Fonts (webfont delivery).",
      "These providers process data on our behalf or under their own published privacy policies. We do not authorize any of them to use your information for their own marketing.",
    ],
  },
  {
    title: "7. Cookies",
    paragraphs: [
      "The public Site sets no cookies. There are no consent banners because there is nothing to consent to — no tracking, advertising, or analytics cookies exist on the Site. A single functional cookie is used only by an internal, password-protected administration area that is not part of the public website and is never set for visitors.",
    ],
  },
  {
    title: "8. Data Retention",
    paragraphs: [
      "Inquiry emails are retained for as long as needed to handle your request and maintain a record of our business correspondence, after which they may be deleted in the ordinary course. You may ask us to delete your inquiry at any time using the contact details below.",
    ],
  },
  {
    title: "9. Your Rights",
    paragraphs: [
      "You may request access to, correction of, or deletion of the personal information you have sent us, and you may ask us to stop contacting you at any time. Depending on where you live, local law (such as the GDPR in the European Economic Area and the United Kingdom, or state privacy laws in the United States) may give you additional rights. To exercise any of these, email contact@elderops.net — we will respond within a reasonable period.",
    ],
  },
  {
    title: "10. Data Security",
    paragraphs: [
      "The Site is served over HTTPS, and form submissions are transmitted over encrypted connections. Because we store no visitor database, the information we hold about you is limited to the email correspondence you initiate. No method of transmission or storage is completely secure, but minimizing what we collect is our first line of defense.",
    ],
  },
  {
    title: "11. International Transfers",
    paragraphs: [
      "Our service providers operate infrastructure in the United States and other countries, so information you submit may be processed outside your own jurisdiction. Where required, transfers rely on the safeguards provided in our providers' data processing terms.",
    ],
  },
  {
    title: "12. Children's Privacy",
    paragraphs: [
      "The Site is a business-to-business service and is not directed to children under 16. We do not knowingly collect personal information from children. If you believe a child has provided us information, contact us and we will delete it.",
    ],
  },
  {
    title: "13. Changes to This Policy",
    paragraphs: [
      'We may update this Privacy Policy from time to time. Changes take effect when posted on this page, and the "Last updated" date above reflects the most recent revision. Material changes will be reflected prominently on this page.',
    ],
  },
  {
    title: "14. Contact",
    paragraphs: [
      "Questions about this Privacy Policy or your information can be sent to contact@elderops.net.",
    ],
  },
];

const Privacy = () => {
  return (
    <section className="bg-bg-cream">
      <div className="container pb-24 pt-36 md:pb-32 md:pt-44">
        <Reveal immediate y={20}>
          <h1 className="font-display text-[clamp(2.2rem,4.6vw,3.6rem)] font-semibold leading-[1.05] tracking-[-0.02em] text-primary">
            Privacy Policy
          </h1>
          <p className="mt-5 font-mono text-[11px] uppercase tracking-[0.18em] text-accent-three">
            Last updated — {LAST_UPDATED}
          </p>
        </Reveal>

        <Reveal immediate delay={0.15} y={24}>
          <div className="mt-14 max-w-3xl space-y-12">
            {SECTIONS.map((section) => (
              <div key={section.title}>
                <h2 className="font-display text-xl font-semibold leading-snug tracking-[-0.01em] text-primary md:text-2xl">
                  {section.title}
                </h2>
                {section.paragraphs.map((paragraph) => (
                  <p
                    key={paragraph.slice(0, 40)}
                    className="mt-4 text-[15px] leading-[1.85] text-accent-one"
                  >
                    {paragraph}
                  </p>
                ))}
              </div>
            ))}
          </div>
        </Reveal>
      </div>
    </section>
  );
};

export default Privacy;
